-- Seed the six fixed Monday-Saturday menu slots without meal photography.
with seed_menu (
  code,
  name,
  day,
  menu_slot,
  protein,
  carbs,
  fat,
  fiber,
  sodium,
  potassium,
  kcal,
  tags_id,
  tags_en,
  desc_id,
  desc_en,
  batch
) as (
  values
    (
      'CPL-MON',
      'Chicken Teriyaki',
      'Monday / Senin',
      1,
      82.4::numeric,
      132.5::numeric,
      26.8::numeric,
      0.14::numeric,
      1380.5::numeric,
      355::numeric,
      1100.8::numeric,
      '["Monday / Senin", "82.4g Protein", "1100.8 Kkal"]'::jsonb,
      '["Monday", "82.4g Protein", "1100.8 Kcal"]'::jsonb,
      'Dada ayam empuk berbalut saus teriyaki manis gurih.',
      'Tender chicken glazed in a sweet and savory teriyaki sauce.',
      'MON-01'
    ),
    (
      'CPL-TUE',
      'Ayam Cabe Ijo',
      'Tuesday / Selasa',
      2,
      79.8::numeric,
      124::numeric,
      29.5::numeric,
      0.14::numeric,
      1290::numeric,
      365::numeric,
      1080.7::numeric,
      '["Tuesday / Selasa", "79.8g Protein", "1080.7 Kkal"]'::jsonb,
      '["Tuesday", "79.8g Protein", "1080.7 Kcal"]'::jsonb,
      'Ayam empuk beraroma sambal cabai hijau segar.',
      'Tender chicken tossed in an aromatic green chili sauce.',
      'TUE-02'
    ),
    (
      'CPL-WED',
      'Chicken Mentai',
      'Wednesday / Rabu',
      3,
      83.2::numeric,
      128.5::numeric,
      31.2::numeric,
      0.14::numeric,
      1420::numeric,
      330::numeric,
      1127.6::numeric,
      '["Wednesday / Rabu", "83.2g Protein", "1127.6 Kkal"]'::jsonb,
      '["Wednesday", "83.2g Protein", "1127.6 Kcal"]'::jsonb,
      'Dada ayam juicy dengan lapisan saus mentai gurih creamy.',
      'Juicy chicken topped with a creamy, savory mentai sauce.',
      'WED-03'
    ),
    (
      'CPL-THU',
      'Sate Padang',
      'Thursday / Kamis',
      4,
      81::numeric,
      122::numeric,
      27.5::numeric,
      0.14::numeric,
      1360::numeric,
      370::numeric,
      1059.5::numeric,
      '["Thursday / Kamis", "81g Protein", "1059.5 Kkal"]'::jsonb,
      '["Thursday", "81g Protein", "1059.5 Kcal"]'::jsonb,
      'Dada ayam empuk dengan kuah sate Padang kaya rempah khas.',
      'Tender chicken coated in a rich and aromatic Padang-style sauce.',
      'THU-04'
    ),
    (
      'CPL-FRI',
      'Oseng Ayam Kecombrang',
      'Friday / Jumat',
      5,
      78.5::numeric,
      125::numeric,
      25::numeric,
      0.14::numeric,
      1240::numeric,
      385::numeric,
      1039::numeric,
      '["Friday / Jumat", "78.5g Protein", "1039 Kkal"]'::jsonb,
      '["Friday", "78.5g Protein", "1039 Kcal"]'::jsonb,
      'Oseng ayam gurih bertabur irisan kecombrang harum.',
      'Savory stir-fried chicken infused with fragrant kecombrang.',
      'FRI-05'
    ),
    (
      'CPL-SAT',
      'Sweet & Sour Crispy Chicken',
      'Saturday / Sabtu',
      6,
      80.5::numeric,
      135::numeric,
      28::numeric,
      0.14::numeric,
      1310::numeric,
      345::numeric,
      1114::numeric,
      '["Saturday / Sabtu", "80.5g Protein", "1114 Kkal"]'::jsonb,
      '["Saturday", "80.5g Protein", "1114 Kcal"]'::jsonb,
      'Ayam renyah berbalut saus asam manis buatan sendiri yang segar.',
      'Crispy chicken tossed in a sweet and tangy homemade sauce.',
      'SAT-06'
    )
),
seed_with_tiers as (
  select
    seed_menu.*,
    current_date
      + (seed_menu.menu_slot - extract(isodow from current_date)::integer) as menu_date,
    (
      select jsonb_object_agg(
        tier.grams::text,
        jsonb_build_object(
          'protein', tier.grams,
          'carbs', round(seed_menu.carbs * tier.grams / seed_menu.protein, 2),
          'fat', round(seed_menu.fat * tier.grams / seed_menu.protein, 2),
          'fiber', round(seed_menu.fiber * tier.grams / seed_menu.protein, 2),
          'sodium', round(seed_menu.sodium * tier.grams / seed_menu.protein, 2),
          'potassium', round(seed_menu.potassium * tier.grams / seed_menu.protein, 2),
          'kcal', round(seed_menu.kcal * tier.grams / seed_menu.protein, 2)
        )
        order by tier.grams
      )
      from unnest(array[25, 40, 60, 80, 100]) as tier(grams)
    ) as nutrition_by_tier
  from seed_menu
)
insert into public.this_week_menu (
  code,
  name,
  day,
  menu_slot,
  menu_date,
  protein,
  carbs,
  fat,
  fiber,
  sodium,
  potassium,
  kcal,
  nutrition_by_tier,
  tags_id,
  tags_en,
  desc_id,
  desc_en,
  batch
)
select
  code,
  name,
  day,
  menu_slot,
  menu_date,
  protein,
  carbs,
  fat,
  fiber,
  sodium,
  potassium,
  kcal,
  nutrition_by_tier,
  tags_id,
  tags_en,
  desc_id,
  desc_en,
  batch
from seed_with_tiers
on conflict (menu_slot) do update
set
  code = excluded.code,
  name = excluded.name,
  day = excluded.day,
  menu_date = excluded.menu_date,
  protein = excluded.protein,
  carbs = excluded.carbs,
  fat = excluded.fat,
  fiber = excluded.fiber,
  sodium = excluded.sodium,
  potassium = excluded.potassium,
  kcal = excluded.kcal,
  nutrition_by_tier = excluded.nutrition_by_tier,
  tags_id = excluded.tags_id,
  tags_en = excluded.tags_en,
  desc_id = excluded.desc_id,
  desc_en = excluded.desc_en,
  batch = excluded.batch,
  updated_at = now();
