import React, { useState } from 'react';
import { CplContext } from './cpl-context';

const INITIAL_MENU_ITEMS = [
  {
    id: "m1",
    code: "CPL-MON",
    name: "Japanese Yakitori Chicken",
    day: "Monday / Senin",
    category: "High Protein",
    protein: 45,
    carbs: 42,
    fat: 14,
    kcal: 474,
    image: "https://images.unsplash.com/photo-1528825871115-3581a5387919?auto=format&fit=crop&w=800&q=80",
    tags_ID: ["Monday / Senin", "Ayam Yakitori Panggang", "Telur & Nasi"],
    tags_EN: ["Monday", "Grilled Yakitori Chicken", "Rice & Egg"],
    desc_ID: "Dada ayam panggang empuk dengan lapisan saus yakitori manis gurih khas Jepang, disajikan dengan nasi dan telur.",
    desc_EN: "Juicy grilled chicken glazed with a sweet & savory yakitori sauce, served with rice and egg.",
    available: true,
    batch: "MON-01"
  },
  {
    id: "m2",
    code: "CPL-TUE",
    name: "Crispy Chili Garlic Chicken (Ayam Cabai Garam)",
    day: "Tuesday / Selasa",
    category: "Lean Muscle",
    protein: 44,
    carbs: 40,
    fat: 15,
    kcal: 471,
    image: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=800&q=80",
    tags_ID: ["Tuesday / Selasa", "Ayam Cabai Garam", "Sambal Tempe Buatan"],
    tags_EN: ["Tuesday", "Chili Garlic Chicken", "Homemade Sambal Tempe"],
    desc_ID: "Ayam renyah beraroma bawang putih dan cabai segar, disajikan dengan nasi, telur, dan sambal tempe buatan sendiri.",
    desc_EN: "Crispy chicken tossed with aromatic garlic and fresh chili, served with rice, egg & homemade sambal tempe.",
    available: true,
    batch: "TUE-02"
  },
  {
    id: "m3",
    code: "CPL-WED",
    name: "Japanese Chicken Nanban",
    day: "Wednesday / Rabu",
    category: "High Protein",
    protein: 46,
    carbs: 44,
    fat: 16,
    kcal: 504,
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    tags_ID: ["Wednesday / Rabu", "Ayam Nanban Renyah", "Saus khas Jepang"],
    tags_EN: ["Wednesday", "Crispy Chicken Nanban", "Japanese Sauce"],
    desc_ID: "Ayam renyah airfried dengan saus nanban khas Jepang kaya rasa, disajikan dengan nasi dan telur.",
    desc_EN: "Crispy airfried chicken coated in a rich Japanese-style nanban sauce, served with rice and egg.",
    available: true,
    batch: "WED-03"
  },
  {
    id: "m4",
    code: "CPL-THU",
    name: "Oyster Glazed Chicken",
    day: "Thursday / Kamis",
    category: "Lean Muscle",
    protein: 45,
    carbs: 38,
    fat: 14,
    kcal: 458,
    image: "https://images.unsplash.com/photo-1555126634-323283e090fa?auto=format&fit=crop&w=800&q=80",
    tags_ID: ["Thursday / Kamis", "Ayam Saus Tiram", "Tempe Bakar"],
    tags_EN: ["Thursday", "Oyster Glazed Chicken", "Grilled Tempe"],
    desc_ID: "Dada ayam empuk berbalut saus tiram gurih manis, disajikan dengan nasi, telur, dan tempe bakar.",
    desc_EN: "Tender chicken glazed in savory oyster sauce, served with rice, egg & grilled tempe.",
    available: true,
    batch: "THU-04"
  },
  {
    id: "m5",
    code: "CPL-FRI",
    name: "Creamy Curry Chicken",
    day: "Friday / Jumat",
    category: "High Protein",
    protein: 43,
    carbs: 45,
    fat: 17,
    kcal: 505,
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=800&q=80",
    tags_ID: ["Friday / Jumat", "Kari Ayam Creamy", "Rempah Kari Gurih"],
    tags_EN: ["Friday", "Creamy Curry Chicken", "Rich Curry Sauce"],
    desc_ID: "Dada ayam empuk yang dimasak lambat dalam saus kari gurih dan creamy, disajikan dengan nasi dan telur.",
    desc_EN: "Tender chicken simmered in rich and creamy curry sauce, served with rice and egg.",
    available: true,
    batch: "FRI-05"
  },
  {
    id: "m6",
    code: "CPL-SAT",
    name: "Crispy Garlic Chicken",
    day: "Saturday / Sabtu",
    category: "Lean Muscle",
    protein: 45,
    carbs: 42,
    fat: 15,
    kcal: 483,
    image: "https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=800&q=80",
    tags_ID: ["Saturday / Sabtu", "Ayam Bawang Renyah", "Tempe Orek"],
    tags_EN: ["Saturday", "Crispy Garlic Chicken", "Tempe Orek"],
    desc_ID: "Ayam goreng renyah keemasan bertabur bawang putih harum, disajikan dengan nasi, telur, dan tempe orek manis gurih.",
    desc_EN: "Golden crispy chicken tossed with fragrant garlic, served with rice, egg & sweet-savory tempe orek.",
    available: true,
    batch: "SAT-06"
  }
];

const INITIAL_ORDERS = [
  {
    id: "ord-101",
    refCode: "CPL-SUB-2026-88",
    customerName: "Alex Pratama",
    phone: "+62 812-3456-7890",
    plan: "5-Day Lunch Plan (5 Meal Boxes)",
    address: "Senopati Suites Tower 2, Jakarta Selatan",
    date: "2026-08-02",
    status: "Approved",
    amount: 350000
  },
  {
    id: "ord-102",
    refCode: "CPL-SUB-2026-92",
    customerName: "Siti Rahmawati",
    phone: "+62 811-9876-5432",
    plan: "14-Day Pro Athlete High Protein",
    address: "Pacific Place Residences Lt. 12, SCBD",
    date: "2026-08-02",
    status: "Pending",
    amount: 1850000
  },
  {
    id: "ord-103",
    refCode: "CPL-SUB-2026-95",
    customerName: "Budi Santoso (TechCorp)",
    phone: "+62 813-1122-3344",
    plan: "Corporate B2B Custom Catering (25 Pax)",
    address: "Gopay Tower, Jl. HR Rasuna Said, Jakarta",
    date: "2026-08-01",
    status: "Delivered",
    amount: 6800000
  }
];

export function CplProvider({ children }) {
  const [menuItems, setMenuItems] = useState(INITIAL_MENU_ITEMS);
  const [orders, setOrders] = useState(INITIAL_ORDERS);
  const [isAdminLoggedIn, setIsAdminLoggedIn] = useState(false);
  const [announcementText, setAnnouncementText] = useState("100% Lab Verified High Protein Meal Prep • Free Delivery Jabodetabek");
  const [language, setLanguage] = useState("EN"); // 'EN' | 'ID'

  // Comprehensive i18n Translation dictionary
  const translations = {
    ID: {
      // Navbar & General
      skipContent: "Lompati ke konten utama",
      pillars: "Pilar Utama",
      labelInspector: "Inspektor Label",
      weeklyMenu: "Menu Mingguan",
      macroCalculator: "Kalkulator Makro",
      b2bCatering: "Katering B2B",
      orderMealPlan: "Pesan Catering",
      switchLanguage: "Pilih Bahasa",
      indonesian: "Indonesia",
      english: "English",

      // Announcement
      announcement: "🔥 HIGH PROTEIN & CUSTOMIZABLE PROTEIN CATERING • 100% Homemade Fresh Makassar • WA +62 899-6727-181",

      // Hero Section
      heroEyebrow: "Katering Harian Tinggi Protein Makassar",
      heroBadge1: "100% Homemade Fresh Prep",
      heroBadge2: "Bebas Pengawet & Rendah Kalori",
      heroTitle1: "GOOD FOOD.",
      heroTitle2: "CLEAR DATA.",
      heroTitle3: "BETTER YOU.",
      heroSubtitle: "Clean Plate Lab adalah katering sehat harian TINGGI PROTEIN & CUSTOMIZABLE PROTEIN di Makassar. Bebas pilih porsi protein harianmu (25g, 60g, 80g, hingga 100g) dalam olahan rumahan (homemade) segar rendah kalori.",
      heroAvgProtein: "Customizable Protein",
      heroAvgProteinDesc: "Bebas Pilih 25g, 60g, 80g & 100g",
      heroWholeFood: "Formulasi Tinggi Protein",
      heroWholeFoodDesc: "Nutrisi Makro Terhitung Presisi",
      heroMacroAcc: "Pengiriman Harian",
      heroMacroAccDesc: "Dimasak & dikirim segar setiap hari",
      heroCtaPrimary: "Pesan Katering Harian",
      heroCtaSecondary: "Inspeksi Label Nutrisi",
      heroFeature1: "Tinggi Protein Harian",
      heroFeature2: "Custom Porsi 25g - 100g",
      heroFeature3: "100% Homemade Fresh",
      heroLabelTitle: "CHICKEN NANBAN",
      heroLabelSub: "KATERING HARIAN TINGGI PROTEIN & CUSTOMIZABLE",
      heroLabelPrepared: "OLAHAN: 100% HOMEMADE",
      heroLabelUseBy: "KEMASAN: FOOD-GRADE SAFE",
      heroLabelBatch: "PETUNJUK: HANGATKAN 30-45S",
      heroPrepToday: "100% HOMEMADE",
      heroUseByDays: "FOOD-GRADE SAFE",
      heroPrepared: "OLAHAN",
      heroUseBy: "KEMASAN",
      heroBatch: "PETUNJUK",
      heroInstructionVal: "HANGATKAN 30-45S",
      heroProtein: "PROTEIN",
      heroCarbs: "KARBOHIDRAT",
      heroFat: "LEMAK",
      heroCalories: "KALORI",

      // Brand Pillars
      pillarsEyebrow: "Standar Utama Katering CPL",
      pillarsTitle: "MENGAPA CLEAN PLATE LAB",
      pillarsSubtitle: "Bagaimana kami merevolusi katering sehat harian di Makassar dengan formulasi tinggi protein, custom porsi 25g - 100g, olahan rumahan (homemade), dan kemasan food-grade.",
      pillar1Title: "Formulasi Tinggi Protein",
      pillar1Desc: "Setiap porsi katering didesain khusus tinggi protein (hingga 100g per porsi) untuk mendukung pembentukan otot kering dan metabolisme harian.",
      pillar2Title: "Customizable Protein Tiers",
      pillar2Desc: "Pilih tingkat protein harianmu secara bebas: 25g, 60g, 80g, atau 100g protein sesuai target energi dan fitness unik Anda.",
      pillar3Title: "100% Olahan Rumahan (Homemade)",
      pillar3Desc: "Setiap hidangan dikemas dalam wadah food-grade khusus yang terjamin kebersihan, higiene, dan aman dipanaskan.",
      pillar1H1: "Pilihan 25g, 60g, 80g & 100g Protein",
      pillar1H2: "Formulasi Tinggi Protein & Rendah Kalori",
      pillar1H3: "Dimasak Segar secara Rumahan Setiap Hari",
      pillar2H1: "Bebas Pengawet Buatan & Bebas Minyak Berlebih",
      pillar2H2: "Formulasi Rendah Kalori untuk Fat Loss & Fitness",
      pillar2H3: "Dimasak & Dikirim Segar Setiap Hari",
      pillar3H1: "Wadah Food-Grade Bebas Racun & BPA-Free",
      pillar3H2: "Higienis & Praktis Aman Dipanaskan",
      pillar3H3: "Diformulasikan Oleh Ahli Gizi Klinis",

      // Label Inspector / Generator
      labelEyebrow: "Inspektor Label Interaktif",
      labelTitle: "TRANSPARANSI MAKRO TANPA RAHASIA",
      labelSubtitle: "Pilih porsi protein untuk melihat spesifikasi nutrisi lengkap laboratorium, komposisi bahan, dan estimasi harga.",
      labelSelectMeal: "Pilih Menu Produk:",
      labelCustomBuilder: "Pilihan Tingkat Protein",
      labelIngredients: "Komposisi Bahan:",
      labelInspectCta: "Pesan Menu Ini Sekarang",
      labelCopySpec: "Salin Spesifikasi Makro",
      labelCopiedSpec: "Spesifikasi Tersalin!",
      labelMealTitle: "Judul Makanan:",
      labelMealPlaceholder: "misal: ULTRA LEAN BISON BOWL",
      labelProteinTarget: "TARGET PROTEIN",
      labelComplexCarbs: "KARBOHIDRAT KOMPLEKS",
      labelHealthyFats: "LEMAK SEHAT",
      labelCustomDesc: "Formulasi lab kustom menggunakan protein grass-fed terverifikasi CPL, biji-bijian kompleks organik, dan lemak cold-pressed.",
      labelSpecTitle: "SPESIFIKASI PRODUK CLEAN PLATE LAB",
      labelStandardStr: "Standard: GOOD FOOD. CLEAR DATA. BETTER YOU.",

      // Menu Section
      menuEyebrow: "Katalog Variasi Menu",
      menuTitle: "VARIASI HIDANGAN KATERING HARIAN",
      menuSubtitle: "Pilihan hidangan tinggi protein & rendah kalori yang disajikan berotasi dalam katering harian CPL.",
      menuFilterAll: "Semua Variasi",
      menuFilterHighProtein: "Tinggi Protein",
      menuFilterLean: "Otot Kering",
      menuFilterPlant: "Nabati",
      menuFilterKeto: "Rendah Karbo",
      menuSelectCta: "Pesan Katering Harian",
      menuAddedCta: "Menu Rotasi Harian",
      menuSampleBadge: "Menu Rotasi Harian",

      // Packaging Section
      packEyebrow: "Standar Kebersihan & Kualitas",
      packTitle: "STANDAR KEMASAN FOOD-GRADE HYGIENIC",
      packSubtitle: "Setiap hidangan Clean Plate Lab dikirim dalam kemasan food-grade terisolasi yang terjamin higienis untuk menjaga kualitas nutrisi.",
      packItem1Title: "Jaminan Kesegaran & Higiene",
      packItem1Desc: "Wadah khusus menjaga keutuhan bahan. Bebas racun, BPA-free, serta dirancang rapat agar makanan tetap segar dan bersih.",
      packItem2Title: "Pengiriman Segar & Hangat",
      packItem2Desc: "Pengiriman terisolasi dalam tas khusus untuk menjaga hidangan tetap hangat, segar, dan siap langsung disantap saat tiba di pintu rumah Anda di Makassar.",
      packItem3Title: "Kemasan Food-Grade Safe",
      packItem3Desc: "Bebas dari racun berbahaya & BPA-free untuk menjamin keamanan konsumsi harian Anda.",
      packBoxRef: "REF BOX: CPL-FOODGRADE-2026",
      pack100Biodegradable: "100% Food-Grade Safe",
      packBoxSlogan: "MAKANAN YANG MEMBERIKAN LEBIH DARI SEJADINYA KENYANG.",
      packThermalSeal: "SEGEL TERMAL:",
      packThermalSealVal: "AKTIF SEGAR",
      packMaterial: "BAHAN:",
      packMaterialVal: "PLASTIK FOOD-GRADE HYGIENIC",
      packMicrowave: "AMAN MICROWAVE:",
      packMicrowaveVal: "YA (30-45 DETIK)",
      packFeature1: "Lengan makanan tersegel kedap udara mencegah oksidasi air",
      packFeature2: "Desain praktis dapat dipanaskan ulang via microwave atau oven",
      packFeature3: "Kode batch cetak langsung di kemasan untuk riwayat audit",

      // Macro Calculator
      calcEyebrow: "Perhitungan Berbasis Sains",
      calcTitle: "KALKULATOR MAKRO HARIAN",
      calcSubtitle: "Hitung kebutuhan kalori dan target nutrisi harianmu secara akurat dengan kontrol interaktif.",
      calcInputSection: "Input Metrik Tubuh",
      calcGender: "Jenis Kelamin",
      calcMale: "Pria",
      calcFemale: "Wanita",
      calcWeightLabel: "BERAT BADAN (KG)",
      calcHeightLabel: "TINGGI BADAN (CM)",
      calcAgeLabel: "USIA (TAHUN)",
      calcYears: "tahun",
      calcActivity: "Tingkat Aktivitas Harian:",
      calcActivitySedentary: "Sedentari (Kerja kantoran, jarang olahraga)",
      calcActivityLight: "Ringan (Olahraga 1-3 hari/minggu)",
      calcActivityModerate: "Moderat (Olahraga 3-5 hari/minggu)",
      calcActivityHeavy: "Aktif Berat (Latihan intensif 6-7 hari/minggu)",
      calcActivityAthlete: "Atlet Profesional / Kerja Fisik Berat",
      calcGoal: "Target Fitness Utama:",
      calcGoalCut: "Turun Lemak",
      calcGoalMaintain: "Jaga Berat",
      calcGoalMuscle: "Bentuk Otot",
      calcResultTitle: "TARGET MAKRO HARIAN",
      calcEnergyNeeds: "Kebutuhan Energi Terhitung",
      calcDailyProtein: "PROTEIN HARIAN",
      calcDailyCarbs: "KARBOHIDRAT HARIAN",
      calcDailyFat: "LEMAK SEHAT",
      calcRecommendationTitle: "Paket Katering CPL Direkomendasikan",
      calcPlanAthlete: "Paket 100g Protein (Rp 60.000)",
      calcPlanCut: "Paket 60g Protein (Rp 40.000)",
      calcPlanWellness: "Paket 25g Protein (Rp 25.000)",
      calcMealsPerDay: "Makan / Hari",
      calcRecSummary: "Target: {protein}g protein. Direkomendasikan: {plan} ({meals} box makanan segar harian).",
      calcSubscribeBtn: "Pesan {plan}",
      calcProteinTargetDesc: "• Target Protein: {ratio}g / kg berat badan.",
      calcBmrEstimate: "• Estimasi BMR:",
      calcFactor: "Faktor:",

      // B2B Corporate Catering
      b2bEyebrow: "Solusi Perusahaan & Acara",
      b2bTitle: "KATERING B2B & SEHAT KANTOR",
      b2bSubtitle: "Tingkatkan produktivitas tim kantor atau pusat kebugaran Anda dengan box katering tinggi protein terverifikasi di Makassar.",
      b2bHeadline: "NUTRISI YANG MEMBERIKAN ENERGI LEBIH UNTUK TIM",
      b2bDesc: "Rasa kantuk setelah makan siang mengurangi produktivitas. Clean Plate Lab menggantikan katering berminyak dengan nutrisi tinggi protein yang menjaga fokus mental sepanjang hari.",
      b2bCard1Title: "Makan Siang Kantor Tech",
      b2bCard1Desc: "Box ramah lingkungan harian berlabel nama karyawan dan makro lengkap.",
      b2bCard2Title: "Pusat Gym & Kebugaran",
      b2bCard2Desc: "Kulkas kemitraan untuk gym CrossFit dan studio kebugaran.",
      b2bFeature1: "Dashboard makro perusahaan & portal preferensi karyawan",
      b2bFeature2: "Pengiriman terkontrol suhu tepat sesuai jam yang diminta",
      b2bFeature3: "Layanan concierge nutrisi khusus perusahaan",
      b2bEstimatorTitle: "ESTIMASI BIAYA PERUSAHAAN",
      b2bTierPricing: "Harga Tier B2B",
      b2bTeamSize: "JUMLAH TIM / KARYAWAN",
      b2bPeopleUnit: "Orang",
      b2bDeliveryDays: "HARI PENGIRIMAN PER MINGGU",
      b2bDaysUnit: "Hari",
      b2bServiceOption: "Opsi Layanan:",
      b2bLunchOnly: "Box Makan Siang",
      b2bFullDay: "Makan Siang + Malam",
      b2bWeeklyMeals: "ESTIMASI BOX PER MINGGU:",
      b2bBoxesPerWk: "box / minggu",
      b2bWeeklyBudget: "ESTIMASI ANGGARAN MINGGUAN:",
      b2bRatePerBox: "Tarif: Rp {rate} / box makan",
      b2bCta: "Minta Proposal Katering B2B",

      // Order Modal
      orderInquiryBadge: "Pemesanan Catering CPL Makassar",
      orderModalTitle: "Formulir Pemesanan Meal Plan CPL",
      orderModalSub: "Pilih tingkat protein dan lengkapi data untuk memesan via WhatsApp.",
      orderCustomerDetails: "Data pemesan",
      orderProteinTier: "Pilih porsi protein",
      orderDeliveryHighlight: "1 box segar, setiap hari",
      orderDeliveryDetail: "Pesanan disiapkan dan diantar 1x sehari setiap Senin-Sabtu. Hari Minggu tidak dihitung.",
      orderDeliverySchedule: "Jadwal & lokasi pengiriman",
      orderSummary: "Ringkasan pesanan",
      orderSelectedPlan: "Paket terpilih",
      orderEstimatedTotal: "Total estimasi",
      orderServingUnit: "porsi",
      orderDayUnit: "hari",
      orderSundayExcluded: "Hari Minggu tidak dihitung",
      orderContinue: "Lanjut",
      orderBack: "Kembali",
      orderName: "Nama Lengkap",
      orderPhone: "Nomor WhatsApp",
      orderPlan: "Pilih Porsi Protein",
      orderSelectProteinLabel: "Pilih Porsi Protein Katering:",
      orderDailyDeliveryNote: "💡 Pengiriman katering harian dikirim 1x sehari (1 Box Makanan / Hari)",
      orderDeliveryPeriodLabel: "Periode Pengiriman",
      orderDateRangeLabel: "Rentang Tanggal:",
      orderEstimatedTotalCostLabel: "Total Estimasi Biaya",
      orderPortionUnit: "/ porsi",
      orderPlanOpt1: "25g Protein Plan - Rp 25.000 / porsi",
      orderPlanOpt2: "60g Protein Plan - Rp 40.000 / porsi",
      orderPlanOpt3: "80g Protein Plan - Rp 50.000 / porsi",
      orderPlanOpt4: "100g Protein Plan - Rp 60.000 / porsi",
      orderPlanOpt5: "Inquiry Katering Perusahaan / B2B Makassar",
      orderAddress: "Alamat Pengiriman Lengkap (Makassar)",
      orderAddressPlaceholder: "Jl. G. Bulusaraung, nama gedung, atau alamat lengkap Anda...",
      orderStartDate: "Tanggal Mulai Delivery",
      orderEndDate: "Tanggal Selesai Delivery",
      orderTotalDays: "Total Hari Delivery",
      orderTotalCost: "Total Biaya (Total Hari × Harga)",
      orderDaysUnit: "Hari",
      orderSubmit: "Kirim Pemesanan via WhatsApp",
      orderGuaranteeNote: "Jaminan Kesegaran Lab • Langsung Terhubung ke WhatsApp CPL",
      orderSuccessMsg: "Pemesanan berhasil dikirim!",
      orderSuccessDetail: "Terima kasih, {name}. Permintaan pemesanan Clean Plate Lab untuk {plan} sedang dibuka di WhatsApp (+62 899-6727-181). Concierge nutrisi kami akan segera memprosesnya.",
      orderBackBtn: "Kembali ke Beranda",

      // Footer
      footerDesc: "Clean Plate Lab — Layanan katering tinggi protein terverifikasi laboratorium pertama di Kota Makassar.",
      footerQuickLinks: "Navigasi Cepat",
      footerKitchenContact: "Dapur & Kontak",
      footerCentralKitchen: "Jalan G. Bulusaraung no. 18AA, RW.01, Pisang Utara, Kec. Ujung Pandang, Kota Makassar, Sulawesi Selatan 90115",
      footerLegal: "Hak Cipta Dilindungi Undang-Undang.",
      footerMadeForTomorrow: "DIBUAT UNTUK HARI ESOK YANG LEBIH BAIK.",
      footerBackToTop: "Kembali Ke Atas",
      adminPortal: "Portal Admin CMS"
    },
    EN: {
      // Navbar & General
      skipContent: "Skip to main content",
      pillars: "Core Pillars",
      labelInspector: "Label Inspector",
      weeklyMenu: "Weekly Menu",
      macroCalculator: "Macro Calculator",
      b2bCatering: "B2B Catering",
      orderMealPlan: "Order Meal Plan",
      switchLanguage: "Select Language",
      indonesian: "Indonesia",
      english: "English",
      announcement: "🔥 HIGH PROTEIN & CUSTOMIZABLE PROTEIN CATERING • 100% Homemade Fresh Makassar • WA +62 899-6727-181",

      // Hero Section
      heroEyebrow: "Daily High Protein Catering Makassar",
      heroBadge1: "100% Fresh Homemade Prep",
      heroBadge2: "Preservative Free & Low Calorie",
      heroTitle1: "GOOD FOOD.",
      heroTitle2: "CLEAR DATA.",
      heroTitle3: "BETTER YOU.",
      heroSubtitle: "Clean Plate Lab is Makassar’s premier HIGH PROTEIN & CUSTOMIZABLE PROTEIN daily healthy catering service. Choose your daily protein level (25g, 60g, 80g, up to 100g) in fresh homemade low calorie meals.",
      heroAvgProtein: "Customizable Protein",
      heroAvgProteinDesc: "Select 25g, 60g, 80g & 100g",
      heroWholeFood: "High Protein Density",
      heroWholeFoodDesc: "Calculated Macro Precision",
      heroMacroAcc: "Fresh Daily Delivery",
      heroMacroAccDesc: "Cooked & delivered fresh daily",
      heroCtaPrimary: "Order Daily Catering",
      heroCtaSecondary: "Inspect Nutrition Label",
      heroFeature1: "High Daily Protein",
      heroFeature2: "Custom 25g - 100g Tiers",
      heroFeature3: "100% Fresh Homemade",
      heroLabelTitle: "CHICKEN NANBAN",
      heroLabelSub: "DAILY HIGH PROTEIN & CUSTOMIZABLE CATERING",
      heroLabelPrepared: "PREP: 100% HOMEMADE",
      heroLabelUseBy: "PACKAGING: FOOD-GRADE SAFE",
      heroLabelBatch: "HEATING: REHEAT 30-45S",
      heroPrepToday: "100% HOMEMADE",
      heroUseByDays: "FOOD-GRADE SAFE",
      heroPrepared: "PREP",
      heroUseBy: "PACKAGING",
      heroBatch: "HEATING",
      heroInstructionVal: "REHEAT 30-45S",
      heroProtein: "PROTEIN",
      heroCarbs: "CARBS",
      heroFat: "FAT",
      heroCalories: "CALORIES",

      // Brand Pillars
      pillarsEyebrow: "The CPL Difference",
      pillarsTitle: "WHY CLEAN PLATE LAB",
      pillarsSubtitle: "How we revolutionize daily healthy catering in Makassar with high protein formulations, custom 25g - 100g protein tiers, fresh homemade cooking, and food-grade packaging.",
      pillar1Title: "High Protein Formulations",
      pillar1Desc: "Every meal portion is specially engineered to deliver high protein density (up to 100g per meal) for lean muscle growth and metabolic support.",
      pillar2Title: "Customizable Protein Tiers",
      pillar2Desc: "Tailor your daily protein intake: select 25g, 60g, 80g, or 100g protein to match your specific energy and fitness goals.",
      pillar3Title: "100% Fresh Homemade Prep",
      pillar3Desc: "Every meal is packed in food-grade safe containers ensuring cleanliness, safety, and reheating convenience.",
      pillar1H1: "Choose 25g, 60g, 80g & 100g Protein",
      pillar1H2: "High Protein & Low Calorie Balance",
      pillar1H3: "Fresh Homemade Batch Cooking Daily",
      pillar2H1: "Zero artificial preservatives or excess oil",
      pillar2H2: "Low calorie formulation for fat loss & fitness",
      pillar2H3: "Cooked & delivered fresh every day",
      pillar3H1: "Custom 25g, 60g, 80g & 100g Protein options",
      pillar3H2: "Low calorie balanced glycemic load",
      pillar3H3: "Formulated by clinical dietitians",

      // Label Inspector / Generator
      labelEyebrow: "Interactive Label Inspector",
      labelTitle: "NO SECRETS. FULL MACRO TRANSPARENCY",
      labelSubtitle: "Select protein tier to inspect complete lab nutrition specs, ingredients list, and price estimates.",
      labelSelectMeal: "Select Meal Product:",
      labelCustomBuilder: "Protein Tier Selection",
      labelIngredients: "Ingredient Composition:",
      labelInspectCta: "Order This Meal Now",
      labelCopySpec: "Copy Macro Specs",
      labelCopiedSpec: "Specs Copied!",
      labelMealTitle: "Meal Title:",
      labelMealPlaceholder: "e.g. ULTRA LEAN BISON BOWL",
      labelProteinTarget: "PROTEIN TARGET",
      labelComplexCarbs: "COMPLEX CARBS",
      labelHealthyFats: "HEALTHY FATS",
      labelCustomDesc: "Custom lab formulation using CPL certified grass-fed proteins, organic complex grains, and cold-pressed fats.",
      labelSpecTitle: "CLEAN PLATE LAB PRODUCT SPEC",
      labelStandardStr: "Standard: Good Food. Clear Data. Better You.",

      // Menu Section
      menuEyebrow: "Daily Menu Catalog",
      menuTitle: "DAILY CATERING DISHES",
      menuSubtitle: "Selection of high-protein & low-calorie dishes served in daily rotation in CPL catering.",
      menuFilterAll: "All Variations",
      menuFilterHighProtein: "High Protein",
      menuFilterLean: "Lean Muscle",
      menuFilterPlant: "Plant Power",
      menuFilterKeto: "Low Carb",
      menuSelectCta: "Order Daily Catering",
      menuAddedCta: "Daily Rotation Dish",
      menuSampleBadge: "Daily Rotation Dish",

      // Packaging Section
      packEyebrow: "Hygiene & Quality Standards",
      packTitle: "FOOD-GRADE HYGIENIC PACKAGING STANDARD",
      packSubtitle: "Every Clean Plate Lab meal is delivered in food-grade insulated containers designed to preserve peak nutritional freshness and cleanliness.",
      packItem1Title: "Freshness & Hygiene Guarantee",
      packItem1Desc: "Custom containers protect ingredient integrity. Non-toxic, BPA-free, and sealed so food stays pristine.",
      packItem2Title: "Fresh & Warm Daily Transit",
      packItem2Desc: "Insulated thermal delivery keeping your meal warm, fresh, and ready to enjoy immediately upon arrival at your doorstep in Makassar.",
      packItem3Title: "Food-Grade Safe Packaging",
      packItem3Desc: "BPA-free non-toxic materials for maximum daily meal consumption safety.",
      packBoxRef: "BOX REF: CPL-FOODGRADE-2026",
      pack100Biodegradable: "100% Food-Grade Safe",
      packBoxSlogan: "MEALS THAT DO MORE THAN FILL.",
      packThermalSeal: "THERMAL SEAL:",
      packThermalSealVal: "ACTIVE FRESH",
      packMaterial: "MATERIAL:",
      packMaterialVal: "HYGIENIC FOOD-GRADE",
      packMicrowave: "MICROWAVE SAFE:",
      packMicrowaveVal: "YES (30-45 SECS)",
      packFeature1: "Hermetically sealed meal sleeves prevent air oxidation",
      packFeature2: "Easy reheatable design for microwave or oven warming",
      packFeature3: "Custom batch code printed directly on sleeve for audit trail",

      // Macro Calculator
      calcEyebrow: "Science-Backed Calculation",
      calcTitle: "DAILY MACRO CALCULATOR",
      calcSubtitle: "Calculate your daily caloric expenditure and target macros using interactive controls.",
      calcInputSection: "Input Body Metrics",
      calcGender: "Gender",
      calcMale: "Male",
      calcFemale: "Female",
      calcWeightLabel: "BODY WEIGHT (KG)",
      calcHeightLabel: "HEIGHT (CM)",
      calcAgeLabel: "AGE (YEARS)",
      calcYears: "yrs",
      calcActivity: "Daily Activity Level:",
      calcActivitySedentary: "Sedentary (Office job, little exercise)",
      calcActivityLight: "Lightly Active (Workout 1-3 days/week)",
      calcActivityModerate: "Moderately Active (Workout 3-5 days/week)",
      calcActivityHeavy: "Very Active (Intense training 6-7 days/week)",
      calcActivityAthlete: "Professional Athlete / Heavy Labor",
      calcGoal: "Primary Fitness Objective:",
      calcGoalCut: "Fat Loss",
      calcGoalMaintain: "Maintain Weight",
      calcGoalMuscle: "Muscle Build",
      calcResultTitle: "DAILY TARGET MACROS",
      calcEnergyNeeds: "Calculated Energy Needs",
      calcDailyProtein: "DAILY PROTEIN",
      calcDailyCarbs: "DAILY CARBS",
      calcDailyFat: "HEALTHY FAT",
      calcRecommendationTitle: "Recommended CPL Catering Package",
      calcPlanAthlete: "100g Protein Plan (Rp 60,000)",
      calcPlanCut: "60g Protein Plan (Rp 40,000)",
      calcPlanWellness: "25g Protein Plan (Rp 25,000)",
      calcMealsPerDay: "Meals / Day",
      calcRecSummary: "Target: {protein}g protein. Recommended: {plan} ({meals} fresh meal boxes daily).",
      calcSubscribeBtn: "Order {plan}",
      calcProteinTargetDesc: "• Protein target: {ratio}g / kg body weight.",
      calcBmrEstimate: "• Estimated BMR:",
      calcFactor: "Factor:",

      // B2B Corporate Catering
      b2bEyebrow: "Corporate & Events Solution",
      b2bTitle: "B2B & OFFICE WELLNESS CATERING",
      b2bSubtitle: "Fuel your tech team, fitness center, or corporate event with high-protein, laboratory-verified meal boxes delivered fresh in Makassar.",
      b2bHeadline: "MEALS THAT DO MORE THAN FILL YOUR TEAM",
      b2bDesc: "Post-lunch brain fog costs companies hours of productivity. Clean Plate Lab replaces heavy, oily traditional catering with balanced, high-protein nutrition that sustains mental focus.",
      b2bCard1Title: "Tech Office Lunch",
      b2bCard1Desc: "Daily individual eco-boxes labeled with employee names & macros.",
      b2bCard2Title: "Gym & Fitness Hubs",
      b2bCard2Desc: "Partner fridge placement for CrossFit boxes and boutique gyms.",
      b2bFeature1: "Custom company macro dashboard & employee preference portal",
      b2bFeature2: "Temperature-controlled thermal delivery at your exact requested hour",
      b2bFeature3: "Dedicated corporate nutrition concierge",
      b2bEstimatorTitle: "CORPORATE COST ESTIMATOR",
      b2bTierPricing: "B2B Tier Pricing",
      b2bTeamSize: "TEAM SIZE / HEADCOUNT",
      b2bPeopleUnit: "People",
      b2bDeliveryDays: "DELIVERY DAYS PER WEEK",
      b2bDaysUnit: "Days",
      b2bServiceOption: "Service Option:",
      b2bLunchOnly: "Lunch Meal Box",
      b2bFullDay: "Lunch + Dinner",
      b2bWeeklyMeals: "ESTIMATED WEEKLY MEALS:",
      b2bBoxesPerWk: "boxes / wk",
      b2bWeeklyBudget: "ESTIMATED WEEKLY BUDGET:",
      b2bRatePerBox: "Rate: Rp {rate} / meal box",
      b2bCta: "Request B2B Corporate Proposal",

      // Order Modal
      orderInquiryBadge: "CPL Order Inquiry Makassar",
      orderModalTitle: "CPL Meal Plan Inquiry Form",
      orderModalSub: "Choose your protein tier and fill details to order via WhatsApp.",
      orderCustomerDetails: "Customer details",
      orderProteinTier: "Choose protein portion",
      orderDeliveryHighlight: "1 fresh box, every day",
      orderDeliveryDetail: "Your meal is prepared and delivered once daily, Monday-Saturday. Sundays are excluded.",
      orderDeliverySchedule: "Delivery schedule & location",
      orderSummary: "Order summary",
      orderSelectedPlan: "Selected plan",
      orderEstimatedTotal: "Estimated total",
      orderServingUnit: "serving",
      orderDayUnit: "day",
      orderSundayExcluded: "Sundays are excluded",
      orderContinue: "Continue",
      orderBack: "Back",
      orderName: "Full Name",
      orderPhone: "WhatsApp Phone Number",
      orderPlan: "Select Protein Tier",
      orderSelectProteinLabel: "Select Catering Protein Portion:",
      orderDailyDeliveryNote: "💡 Daily catering delivery is sent 1x daily (1 Meal Box / Day)",
      orderDeliveryPeriodLabel: "Delivery Period",
      orderDateRangeLabel: "Date Range:",
      orderEstimatedTotalCostLabel: "Total Estimated Cost",
      orderPortionUnit: "/ portion",
      orderPlanOpt1: "25g Protein Plan - Rp 25,000 / portion",
      orderPlanOpt2: "60g Protein Plan - Rp 40,000 / portion",
      orderPlanOpt3: "80g Protein Plan - Rp 50,000 / portion",
      orderPlanOpt4: "100g Protein Plan - Rp 60,000 / portion",
      orderPlanOpt5: "Corporate / B2B Catering Inquiry Makassar",
      orderAddress: "Full Delivery Address (Makassar)",
      orderAddressPlaceholder: "Street address, building name, unit number in Makassar...",
      orderStartDate: "Delivery Start Date",
      orderEndDate: "Delivery End Date",
      orderTotalDays: "Total Delivery Days",
      orderTotalCost: "Total Cost (Total Days × Price)",
      orderDaysUnit: "Days",
      orderSubmit: "Submit Order via WhatsApp",
      orderGuaranteeNote: "Lab Fresh Guarantee • Direct Connect to CPL WhatsApp",
      orderSuccessMsg: "Order request sent successfully!",
      orderSuccessDetail: "Thank you, {name}. Your Clean Plate Lab order request for {plan} is opening in WhatsApp (+62 899-6727-181). Our nutrition concierge will process it shortly.",
      orderBackBtn: "Back to Overview",

      // Footer
      footerDesc: "Clean Plate Lab — Indonesia’s premier laboratory-verified high protein meal prep service based in Makassar City.",
      footerQuickLinks: "Quick Navigation",
      footerKitchenContact: "Kitchen & Contact",
      footerCentralKitchen: "Jalan G. Bulusaraung no. 18AA, RW.01, Pisang Utara, Ujung Pandang, Makassar City, South Sulawesi 90115",
      footerLegal: "All rights reserved.",
      footerMadeForTomorrow: "MADE FOR A BETTER TOMORROW.",
      footerBackToTop: "Back To Top",
      adminPortal: "CMS Admin Portal"
    }
  };

  const t = (key) => {
    return translations[language]?.[key] || translations['EN']?.[key] || key;
  };

  // Add new meal item
  const addMenuItem = (item) => {
    const newItem = {
      ...item,
      id: `m${Date.now()}`,
      code: item.code || `CPL-0${menuItems.length + 14}`,
      available: true
    };
    setMenuItems(prev => [newItem, ...prev]);
  };

  // Update existing meal item
  const updateMenuItem = (id, updatedFields) => {
    setMenuItems(prev => prev.map(item => item.id === id ? { ...item, ...updatedFields } : item));
  };

  // Delete meal item
  const deleteMenuItem = (id) => {
    setMenuItems(prev => prev.filter(item => item.id !== id));
  };

  // Add new order
  const addOrder = (orderData) => {
    const newOrder = {
      ...orderData,
      id: `ord-${Date.now()}`,
      refCode: `CPL-SUB-2026-${Math.floor(10 + Math.random() * 90)}`,
      date: new Date().toISOString().split('T')[0],
      status: "Pending"
    };
    setOrders(prev => [newOrder, ...prev]);
  };

  // Update order status
  const updateOrderStatus = (id, status) => {
    setOrders(prev => prev.map(ord => ord.id === id ? { ...ord, status } : ord));
  };

  return (
    <CplContext.Provider value={{
      menuItems,
      addMenuItem,
      updateMenuItem,
      deleteMenuItem,
      orders,
      addOrder,
      updateOrderStatus,
      isAdminLoggedIn,
      setIsAdminLoggedIn,
      announcementText,
      setAnnouncementText,
      language,
      setLanguage,
      t
    }}>
      {children}
    </CplContext.Provider>
  );
}
